version: 2
jobs:
  build:
    docker:
      - image: node:8.6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:ci
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_artifacts:
          path: ~/junit
          prefix: tests
          when: always
      - store_artifacts:
          path: coverage
          prefix: coverage
          when: always
      - store_test_results:
          path: ~/junit
          when: always
